In [1]:
import numpy as np

In [2]:
mtx = np.array([[1,2,3],[4,5,6],[7,8,9]])
print (mtx)

#SLICING
subMtx = mtx[0:2, 1:3]
print(subMtx)

#INDEX

ele = mtx[1,2]
print(ele)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
6


In [3]:
#element wise multiplication 

a = np.array([2,4,6])
b = np.array([5,10,15])

mulRes = np.multiply(a,b)
print(mulRes)

[10 40 90]


In [4]:
#Matrix multiplication 

dotRes = np.dot(a,b)
print(dotRes)

140


In [5]:
#exponential 
expRes = np.exp(a)
print(expRes)

[  7.3890561   54.59815003 403.42879349]


In [6]:
#broadcasting in action 

matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
vector = np.array([1,0,1])
result = matrix + vector
print(result)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


In [7]:
#boolean indexing 
data = np.array([10, 20, 30, 40, 50])
filtered = data[data >35]
print(filtered)

[40 50]


In [11]:
#initialize 

weights = np.random.randn(5)
print("Original weights: ", weights)

Original weights:  [-1.03931009  0.78101114  0.96362717 -0.92982562  1.21760195]


In [12]:
learning_rate = 0.01
gradient = np.array([0.5, -0.1, 0.8, -0.05, 0.9])
weights -= learning_rate* gradient
print("Adjusted weights: ", weights)

Adjusted weights:  [-1.04431009  0.78201114  0.95562717 -0.92932562  1.20860195]


In [13]:
#sample sentences
sentence = "I am learning AI"

#Convert to 1-hot encoded vecotr

vocab = sorted(set(sentence.split()))
one_hot_vectors = np.zeros((len(sentence.split()), len(vocab)))

for i, word in enumerate(sentence.split()):
    one_hot_vectors[i, vocab.index(word)] = 1
    
print(one_hot_vectors)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]
