In [4]:
#pip install opencv-python
import cv2

#load an image
image = cv2.imread('starbunnyy.jpg')
print(image.shape, " , are the channels for our raw starbunny")



(1024, 1024, 3)  , are the channels for our raw starbunny


In [5]:
import numpy as np

In [6]:
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
print(gray.shape, ", are the channels for gray starbunny")
hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)


(1024, 1024) , are the channels for gray starbunny


In [7]:
print(image[:,:,2])

[[ 7  8  8 ... 12 10 11]
 [ 5  8  6 ... 19 11 17]
 [ 7 11  8 ... 11 11  4]
 ...
 [14 14 14 ...  9  7  7]
 [17 13 14 ...  7  8 10]
 [13 13 15 ...  8  8  7]]


blue, green, red = cv2.split(image)

cv2.imshow('Blue Bunny', blue)
cv2.imshow('Green Bunny', green)
cv2.imshow('Red Bunny', red)
cv2.waitKey(5000) 
cv2.destroyAllWindows()

In [8]:
blue, green, red = cv2.split(image)

In [9]:
zeros = np.zeros(blue.shape, np.uint8)

bBunny = cv2.merge([blue,zeros,zeros])
gBunny = cv2.merge([zeros,green,zeros])
rBunny = cv2.merge([zeros,zeros,red])

cv2.imshow('Blue Bunny', bBunny)
cv2.imshow('Green Bunny', gBunny)
cv2.imshow('Red Bunny', rBunny)
cv2.waitKey(5000) 
cv2.destroyAllWindows()

In [ ]:

import matplotlib.pyplot as plt

#historogram for our grayscale

plt.hist(gray.ravel(), 256, [0, 256])
plt.title('Grayscale Histogram')
plt.xlabel('Pixel Intensity')
plt.ylabel('Frequency')

In [10]:
#Histogram for Equalization
equalized = cv2.equalizeHist(gray)

#display the original image

cv2.imshow('Original Image', gray)
cv2.imshow('Equalized Image', equalized)
cv2.waitKey(5000) 
cv2.destroyAllWindows()


In [11]:
#increase brightness
brightened = cv2.convertScaleAbs(image, alpha=1, beta=50)

cv2.imshow('Original Image', image)
cv2.imshow('Brightened Image', brightened)
cv2.waitKey(5000)
cv2.destroyAllWindows()