In [1]:
import numpy as np

In [2]:
oneDimension = np.array([0,2,4,6])
print(oneDimension)

[0 2 4 6]


In [3]:
twoDimension = np.array([[1,2], [3,4], [5,6]])
print(twoDimension)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
print(twoDimension.shape)

(3, 2)


In [6]:
twoDim_reshape = twoDimension.reshape(2,3)

In [7]:
print(twoDim_reshape)

[[1 2 3]
 [4 5 6]]


In [8]:
zeroMatrix = np.zeros((2,2))
print(zeroMatrix)

[[0. 0.]
 [0. 0.]]


In [10]:
oneMatrix = np.ones((2,2))
print(oneMatrix)

[[1. 1.]
 [1. 1.]]


In [11]:
a = np.array([2,2,2])
b = np.array([8, 8, 8])

print(a+b)

[10 10 10]


In [12]:
output = np.dot(a,b)
print(output)

48


In [13]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix[0:2, 1:3])

[[2 3]
 [5 6]]
